import torch
import numpy as np
import random



def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def cheby(i, x):
    if i == 0:
        return 1
    elif i == 1:
        return x
    else:
        T0 = 1
        T1 = x
        for ii in range(2, i + 1):
            T2 = 2 * x * T1 - T0
            T0, T1 = T1, T2
        return T2

def add_self_loops(edge_index, edge_weight, fill_value, num_nodes):
    loop_index = torch.arange(0, num_nodes, dtype=torch.long, device=edge_index.device)
    loop_index = loop_index.unsqueeze(0).repeat(2, 1)
    edge_index = torch.cat([edge_index, loop_index], dim=1)
    loop_weight = torch.full((num_nodes,), fill_value, dtype=edge_weight.dtype, device=edge_weight.device)
    edge_weight = torch.cat([edge_weight, loop_weight], dim=0)
    return edge_index, edge_weight


def get_dataset_specific_settings(dataset):

    specific_settings = {
        "actor": {
            "dataset": "actor",
            "seed": 42,
            "device": "cuda:0",
            "gpu": 0,
            "tasks": ["pretrain", "finetune", "linear", "edge"],
            "skip_pretrain": False,
            "model_path": None,
            "freeze_encoder": False,
            "in_dim": None,
            "hidden_dim": 512,
            "K": 8,
            "dropout": 0.5,
            "dprate": 0.4,
            "is_bns": True,
            "act_fn": "relu",
            "Lev": 5,
            "s": 2,
            "n": 2,
            "FrameType": "Haar",
            "HighpassFilter": "DOS",
            "LowpassFilter": "g_low_pass",
            "epochs": 400,
            "lr": 0.002,
            "wd": 5e-4,
            "lr1": 0.002,
            "wd1": 5e-4,
            "lr2": 0.002,
            "wd2": 5e-4,
            "patience": 100,
            "ft_lr": 1e-3,
            "ft_epochs": 200,
            "ft_wd": 1e-6,
            "lambda_contrast": 0.2,
            "lambda_ortho": 0.1,
            "lambda_edge": 0.1,
            "noise_scale": 0.1,
            "grad_clip": 1.0
        },
        "amazon": {
            "dataset": "amazon",
            "seed": 42,
            "device": "cuda:0",
            "gpu": 0,
            "tasks": ["pretrain", "finetune", "linear", "edge"],
            "skip_pretrain": False,
            "model_path": None,
            "freeze_encoder": False,
            "in_dim": None,
            "hidden_dim": 512,
            "K": 8,
            "dropout": 0.5,
            "dprate": 0.4,
            "is_bns": True,
            "act_fn": "relu",
            "Lev": 5,
            "s": 2,
            "n": 2,
            "FrameType": "Haar",
            "HighpassFilter": "DOS",
            "LowpassFilter": "g_low_pass",
            "epochs": 400,
            "lr": 0.002,
            "wd": 5e-4,
            "lr1": 0.002,
            "wd1": 5e-4,
            "lr2": 0.002,
            "wd2": 5e-4,
            "patience": 100,
            "ft_lr": 1e-3,
            "ft_epochs": 200,
            "ft_wd": 1e-6,
            "lambda_contrast": 0.2,
            "lambda_ortho": 0.1,
            "lambda_edge": 0.1,
            "noise_scale": 0.1,
            "grad_clip": 1.0
        },
        "cora_coauthorship": {
            "dataset": "cora_coauthorship",
            "seed": 42,
            "device": "cuda:0",
            "gpu": 0,
            "tasks": ["pretrain", "finetune", "linear"],
            "skip_pretrain": False,
            "model_path": None,
            "freeze_encoder": False,
            "in_dim": None,
            "hidden_dim": 384,
            "K": 5,
            "dropout": 0.4,
            "dprate": 0.3,
            "is_bns": True,
            "act_fn": "relu",
            "Lev": 5,
            "s": 2,
            "n": 2,
            "FrameType": "Haar",
            "HighpassFilter": "DOS",
            "LowpassFilter": "g_low_pass",
            "epochs": 400,
            "lr": 0.002,
            "wd": 5e-4,
            "lr1": 0.002,
            "wd1": 5e-4,
            "lr2": 0.002,
            "wd2": 5e-4,
            "patience": 50,
            "ft_lr": 1e-3,
            "ft_epochs": 300,
            "ft_wd": 1e-6,
            "lambda_contrast": 0.5,
            "lambda_ortho": 0.1,
            "lambda_edge": 0.1,
            "noise_scale": 0.1,
            "grad_clip": 1.0
        },
        "citeseer": {
            "dataset": "citeseer",
            "seed": 42,
            "device": "cuda:0",
            "gpu": 0,
            "tasks": ["pretrain", "finetune", "linear", "edge"],
            "skip_pretrain": False,
            "model_path": None,
            "freeze_encoder": False,
            "in_dim": None,
            "hidden_dim": 512,
            "K": 8,
            "dropout": 0.5,
            "dprate": 0.4,
            "is_bns": True,
            "act_fn": "relu",
            "Lev": 5,
            "s": 2,
            "n": 2,
            "FrameType": "Haar",
            "HighpassFilter": "DOS",
            "LowpassFilter": "g_low_pass",
            "epochs": 300,
            "lr": 0.003,
            "wd": 5e-4,
            "lr1": 0.003,
            "wd1": 5e-4,
            "lr2": 0.003,
            "wd2": 5e-4,
            "patience": 100,
            "ft_lr": 1e-3,
            "ft_epochs": 200,
            "ft_wd": 1e-6,
            "lambda_contrast": 0.2,
            "lambda_ortho": 0.1,
            "lambda_edge": 0.1,
            "noise_scale": 0.1,
            "grad_clip": 1.0
        },
        "pubmed": {
            "dataset": "pubmed",
            "seed": 42,
            "device": "cuda:0",
            "gpu": 0,
            "tasks": ["pretrain", "finetune", "linear", "edge"],
            "skip_pretrain": False,
            "model_path": None,
            "freeze_encoder": False,
            "in_dim": None,
            "hidden_dim": 768,
            "K": 10,
            "dropout": 0.6,
            "dprate": 0.5,
            "is_bns": True,
            "act_fn": "relu",
            "Lev": 5,
            "s": 2,
            "n": 2,
            "FrameType": "Haar",
            "HighpassFilter": "DOS",
            "LowpassFilter": "g_low_pass",
            "epochs": 400,
            "lr": 0.002,
            "wd": 3e-4,
            "lr1": 0.002,
            "wd1": 3e-4,
            "lr2": 0.002,
            "wd2": 3e-4,
            "patience": 100,
            "ft_lr": 1e-3,
            "ft_epochs": 200,
            "ft_wd": 1e-6,
            "lambda_contrast": 0.25,
            "lambda_ortho": 0.1,
            "lambda_edge": 0.1,
            "noise_scale": 0.1,
            "grad_clip": 1.0
        },
        "pokec": {
            "dataset": "pokec",
            "seed": 42,
            "device": "cuda:0",
            "gpu": 0,
            "tasks": ["pretrain", "finetune", "linear", "edge"],
            "skip_pretrain": False,
            "model_path": None,
            "freeze_encoder": False,
            "in_dim": None,
            "hidden_dim": 512,
            "K": 8,
            "dropout": 0.5,
            "dprate": 0.4,
            "is_bns": True,
            "act_fn": "relu",
            "Lev": 5,
            "s": 2,
            "n": 2,
            "FrameType": "Haar",
            "HighpassFilter": "DOS",
            "LowpassFilter": "g_low_pass",
            "epochs": 400,
            "lr": 0.002,
            "wd": 5e-4,
            "lr1": 0.002,
            "wd1": 5e-4,
            "lr2": 0.002,
            "wd2": 5e-4,
            "patience": 100,
            "ft_lr": 1e-3,
            "ft_epochs": 200,
            "ft_wd": 1e-6,
            "lambda_contrast": 0.2,
            "lambda_ortho": 0.1,
            "lambda_edge": 0.1,
            "noise_scale": 0.1,
            "grad_clip": 1.0
        },
        "twitch": {
            "dataset": "twitch",
            "seed": 42,
            "device": "cuda:0",
            "gpu": 0,
            "tasks": ["pretrain", "finetune", "linear", "edge"],
            "skip_pretrain": False,
            "model_path": None,
            "freeze_encoder": False,
            "in_dim": None,
            "hidden_dim": 512,
            "K": 8,
            "dropout": 0.5,
            "dprate": 0.4,
            "is_bns": True,
            "act_fn": "relu",
            "Lev": 5,
            "s": 2,
            "n": 2,
            "FrameType": "Haar",
            "HighpassFilter": "DOS",
            "LowpassFilter": "g_low_pass",
            "epochs": 400,
            "lr": 0.002,
            "wd": 5e-4,
            "lr1": 0.002,
            "wd1": 5e-4,
            "lr2": 0.002,
            "wd2": 5e-4,
            "patience": 100,
            "ft_lr": 1e-3,
            "ft_epochs": 200,
            "ft_wd": 1e-6,
            "lambda_contrast": 0.2,
            "lambda_ortho": 0.1,
            "lambda_edge": 0.1,
            "noise_scale": 0.1,
            "grad_clip": 1.0
        },
        "aminer": {
            "dataset": "aminer",
            "seed": 42,
            "device": "cuda:0",
            "gpu": 0,
            "tasks": ["pretrain", "finetune", "linear", "edge"],
            "skip_pretrain": False,
            "model_path": None,
            "freeze_encoder": False,
            "in_dim": None,
            "hidden_dim": 384,
            "K": 4,
            "dropout": 0.3,
            "dprate": 0.2,
            "is_bns": True,
            "act_fn": "relu",
            "Lev": 5,
            "s": 2,
            "n": 2,
            "FrameType": "Haar",
            "HighpassFilter": "Linear",
            "LowpassFilter": "g_low_pass",
            "epochs": 350,
            "lr": 0.001,
            "wd": 2e-4,
            "lr1": 0.001,
            "wd1": 2e-4,
            "lr2": 0.001,
            "wd2": 2e-4,
            "patience": 100,
            "ft_lr": 1e-3,
            "ft_epochs": 200,
            "ft_wd": 1e-6,
            "lambda_contrast": 0.35,
            "lambda_ortho": 0.1,
            "lambda_edge": 0.1,
            "noise_scale": 0.1,
            "grad_clip": 1.0
        },
        "cora_cocitation": {
            "dataset": "cora_cocitation",
            "seed": 42,
            "device": "cuda:0",
            "gpu": 0,
            "tasks": ["finetune", "linear",],
            "skip_pretrain": False,
            "model_path": None,
            "freeze_encoder": False,
            "in_dim": None,
            "hidden_dim": 256,
            "K": 6,
            "dropout": 0.4,
            "dprate": 0.3,
            "is_bns": True,
            "act_fn": "relu",
            "Lev": 5,
            "s": 2,
            "n": 2,
            "FrameType": "Haar",
            "HighpassFilter": "g_high_pass",
            "LowpassFilter": "g_low_pass",
            "epochs": 300,
            "lr": 0.002,
            "wd": 1e-4,
            "lr1": 0.002,
            "wd1": 1e-4,
            "lr2": 0.002,
            "wd2": 1e-4,
            "patience": 100,
            "ft_lr": 1e-3,
            "ft_epochs": 200,
            "ft_wd": 1e-6,
            "lambda_contrast": 0.15,
            "lambda_ortho": 0.1,
            "lambda_edge": 0.1,
            "noise_scale": 0.1,
            "grad_clip": 1.0
        },
        "cora_coauth": {
            "dataset": "cora_coauth",
            "seed": 42,
            "device": "cuda:0",
            "gpu": 0,
            "tasks": ["finetune", "linear"],
            "skip_pretrain": False,
            "model_path": None,
            "freeze_encoder": False,
            "in_dim": None,
            "hidden_dim": 256,
            "K": 3,
            "dropout": 0.2,
            "dprate": 0.2,
            "is_bns": True,
            "act_fn": "relu",
            "Lev": 5,
            "s": 2,
            "n": 2,
            "FrameType": "Haar",
            "HighpassFilter": "Linear",
            "LowpassFilter": "g_low_pass",
            "epochs": 400,
            "lr": 0.001,
            "wd": 1e-4,
            "lr1": 0.001,
            "wd1": 1e-4,
            "lr2": 0.001,
            "wd2": 1e-4,
            "patience": 100,
            "ft_lr": 1e-3,
            "ft_epochs": 200,
            "ft_wd": 1e-6,
            "lambda_contrast": 0.4,
            "lambda_ortho": 0.1,
            "lambda_edge": 0.1,
            "noise_scale": 0.1,
            "grad_clip": 1.0
        },
        "imdb": {
            "dataset": "imdb",
            "seed": 42,
            "device": "cuda:0",
            "gpu": 0,
            "tasks": ["pretrain", "finetune", "linear", "edge"],
            "skip_pretrain": False,
            "model_path": None,
            "freeze_encoder": False,
            "in_dim": None,
            "hidden_dim": 512,
            "K": 9,
            "dropout": 0.6,
            "dprate": 0.5,
            "is_bns": True,
            "act_fn": "relu",
            "Lev": 5,
            "s": 2,
            "n": 2,
            "FrameType": "Haar",
            "HighpassFilter": "Eigen",
            "LowpassFilter": "g_low_pass",
            "epochs": 500,
            "lr": 0.001,
            "wd": 1e-4,
            "lr1": 0.001,
            "wd1": 1e-4,
            "lr2": 0.001,
            "wd2": 1e-4,
            "patience": 100,
            "ft_lr": 1e-3,
            "ft_epochs": 200,
            "ft_wd": 1e-6,
            "lambda_contrast": 0.3,
            "lambda_ortho": 0.1,
            "lambda_edge": 0.1,
            "noise_scale": 0.1,
            "grad_clip": 1.0
        },
        "modelnet_40": {
            "dataset": "modelnet_40",
            "seed": 42,
            "device": "cuda:0",
            "gpu": 0,
            "tasks": ["pretrain", "finetune", "linear", "edge"],
            "skip_pretrain": False,
            "model_path": None,
            "freeze_encoder": False,
            "in_dim": None,
            "hidden_dim": 512,
            "K": 7,
            "dropout": 0.5,
            "dprate": 0.4,
            "is_bns": True,
            "act_fn": "relu",
            "Lev": 5,
            "s": 2,
            "n": 2,
            "FrameType": "Haar",
            "HighpassFilter": "DOS",
            "LowpassFilter": "g_low_pass",
            "epochs": 200,
            "lr": 0.005,
            "wd": 5e-4,
            "lr1": 0.005,
            "wd1": 5e-4,
            "lr2": 0.005,
            "wd2": 5e-4,
            "patience": 100,
            "ft_lr": 1e-3,
            "ft_epochs": 200,
            "ft_wd": 1e-6,
            "lambda_contrast": 0.1,
            "lambda_ortho": 0.1,
            "lambda_edge": 0.1,
            "noise_scale": 0.1,
            "grad_clip": 1.0
        },
        "house": {
            "dataset": "house",
            "seed": 42,
            "device": "cuda:0",
            "gpu": 0,
            "tasks": ["pretrain", "finetune", "linear", "edge"],
            "skip_pretrain": False,
            "model_path": None,
            "freeze_encoder": False,
            "in_dim": None,
            "hidden_dim": 128,
            "K": 5,
            "dropout": 0.3,
            "dprate": 0.3,
            "is_bns": True,
            "act_fn": "relu",
            "Lev": 5,
            "s": 2,
            "n": 2,
            "FrameType": "Haar",
            "HighpassFilter": "DOS",
            "LowpassFilter": "g_low_pass",
            "epochs": 300,
            "lr": 0.002,
            "wd": 5e-4,
            "lr1": 0.002,
            "wd1": 5e-4,
            "lr2": 0.002,
            "wd2": 5e-4,
            "patience": 100,
            "ft_lr": 1e-3,
            "ft_epochs": 200,
            "ft_wd": 1e-6,
            "lambda_contrast": 0.25,
            "lambda_ortho": 0.1,
            "lambda_edge": 0.1,
            "noise_scale": 0.1,
            "grad_clip": 1.0
        },
    }

    if dataset in specific_settings:
        return specific_settings[dataset]
    else:
        # 默认设置，如果数据集不在列表中
        return {
            "dataset": dataset,
            "seed": 42,
            "device": "cuda:0",
            "gpu": 0,
            "tasks": ["pretrain", "finetune", "linear", "edge"],
            "skip_pretrain": False,
            "model_path": None,
            "freeze_encoder": False,
            "in_dim": None,
            "hidden_dim": 512,
            "K": 7,
            "dropout": 0.5,
            "dprate": 0.4,
            "is_bns": True,
            "act_fn": "relu",
            "Lev": 5,
            "s": 2,
            "n": 2,
            "FrameType": "Haar",
            "HighpassFilter": "DOS",
            "LowpassFilter": "g_low_pass",
            "epochs": 200,
            "lr": 0.005,
            "wd": 5e-4,
            "lr1": 0.005,
            "wd1": 5e-4,
            "lr2": 0.005,
            "wd2": 5e-4,
            "patience": 100,
            "ft_lr": 1e-3,
            "ft_epochs": 200,
            "ft_wd": 1e-6,
            "lambda_contrast": 0.1,
            "lambda_ortho": 0.1,
            "lambda_edge": 0.1,
            "noise_scale": 0.1,
            "grad_clip": 1.0
        }

